name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        id: publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.PS_CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.PS_CLOUDFLARE_ACCOUNT_ID }}
          projectName: openfilter
          directory: site
          branch: ${{ github.head_ref || github.ref_name }}
          commitHash: ${{ github.sha }}

      - name: Comment with Preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `${{ steps.publish.outputs.url }}`
            const sha = '${{ github.event.pull_request.head.sha }}'.substring(0, 7)
            const comment = `### 🚀 Preview Deployed\n| Commit | Preview URL |\n|--------|-------------|\n| \`${sha}\` | ${url} |`

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
